package com.appspot.livelove.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.google.appengine.api.datastore.Key;

import org.slim3.datastore.Attribute;
import org.slim3.datastore.Model;
import org.slim3.datastore.ModelRef;

@Model(schemaVersion = 1)
public class Artist implements Serializable {

    private static final long serialVersionUID = 1L;

    @Attribute(primaryKey = true)
    private Key key;

    @Attribute(version = true)
    private Long version;

    private String name;

    private boolean isSolo;

    private List<String> anotherNames;

    private String description;

    private boolean isAutoGenerated;

    private ModelRef<Live> joinedLiveRef =
            new ModelRef<Live>(Live.class);

    private ModelRef<UserAccount> registUserAccountRef =
        new ModelRef<UserAccount>(UserAccount.class);

    private Date registDate;

    private Date lastUpdateDate;

    private ModelRef<UserAccount> lastUpdateUserAccountRef =
        new ModelRef<UserAccount>(UserAccount.class);

    private boolean isDeleted;

    /**
     * Returns the key.
     *
     * @return the key
     */
    public Key getKey() {
        return key;
    }

    /**
     * Sets the key.
     *
     * @param key
     *            the key
     */
    public void setKey(Key key) {
        this.key = key;
    }

    /**
     * Returns the version.
     *
     * @return the version
     */
    public Long getVersion() {
        return version;
    }

    /**
     * Sets the version.
     *
     * @param version
     *            the version
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isSolo() {
        return isSolo;
    }

    public void setSolo(boolean isSolo) {
        this.isSolo = isSolo;
    }

    public List<String> getAnotherNames() {
        return anotherNames;
    }

    public void setAnotherNames(List<String> anotherNames) {
        this.anotherNames = anotherNames;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public void setAutoGenerated(boolean isAutoGenerated) {
        this.isAutoGenerated = isAutoGenerated;
    }

    public ModelRef<Live> getJoinedLiveRef() {
        return joinedLiveRef;
    }

    public Date getRegistDate() {
        return registDate;
    }

    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    public ModelRef<UserAccount> getRegistUserAccountRef() {
        return registUserAccountRef;
    }

    public ModelRef<UserAccount> getLastUpdateUserAccountRef() {
        return lastUpdateUserAccountRef;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    public boolean isDeleted() {
        return isDeleted;
    }

    public void setDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((key == null) ? 0 : key.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        Artist other = (Artist) obj;
        if (key == null) {
            if (other.key != null) {
                return false;
            }
        } else if (!key.equals(other.key)) {
            return false;
        }
        return true;
    }
}
